/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.doctor;

import business.EcoSystem;
import business.enterprisepkg.Enterprise;
import business.organizationpkg.Organization;
import business.personpkg.Person;
import business.userAccountpkg.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrivatsanaragund
 */
public class DoctorProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorProfileJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private Organization organization;

    public DoctorProfileJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.ecoSystem = business;

        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        firstName = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        town = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtTown = new javax.swing.JTextField();
        zipCode = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        emailID1 = new javax.swing.JLabel();
        emailID2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Doctor,");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, 52));

        btnBack.setBackground(new java.awt.Color(102, 102, 255));
        btnBack.setText("<Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 860, 70, 20));

        firstName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        firstName.setText("First Name:");
        add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 113, -1, 52));

        txtFname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtFname.setEnabled(false);
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 113, 460, 52));

        LastName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LastName.setText("Last Name:");
        add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, -1, 52));

        txtLname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtLname.setEnabled(false);
        add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 177, 462, 52));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Country:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 247, -1, 52));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("State:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 324, -1, 52));

        address1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        address1.setText("Address : ");
        add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 397, -1, 52));

        town.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        town.setText("Town/City: ");
        add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 455, 92, 52));

        txtState.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtState.setEnabled(false);
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 324, 462, 52));

        txtTown.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtTown.setEnabled(false);
        add(txtTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 455, 462, 52));

        zipCode.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        zipCode.setText("Zip Code:");
        add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 525, -1, 52));

        txtZip.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtZip.setEnabled(false);
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 525, 462, 52));

        phoneNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        phoneNumber.setText("Phone Number:");
        add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 595, -1, 52));

        txtPhoneNo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPhoneNo.setEnabled(false);
        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 595, 462, 52));

        emailID.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        emailID.setText("Email Address:");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 665, -1, 52));

        txtEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtEmail.setEnabled(false);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 665, 462, 52));

        txtAddress.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtAddress.setEnabled(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 397, 462, 52));

        txtCountry.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtCountry.setEnabled(false);
        add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 247, 462, 52));

        btnSave.setBackground(new java.awt.Color(102, 102, 255));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 856, 70, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 856, 80, -1));

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPassword.setEnabled(false);
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 792, 462, -1));

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtUsername.setEnabled(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 752, 462, -1));

        emailID1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        emailID1.setText("Username:");
        add(emailID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 752, -1, -1));

        emailID2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        emailID2.setText("Password:");
        add(emailID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 794, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtFname.setEnabled(true);
        txtAddress.setEnabled(true);
        txtCountry.setEnabled(true);
        txtEmail.setEnabled(true);
        txtLname.setEnabled(true);
        txtPhoneNo.setEnabled(true);
        txtPhoneNo.setEnabled(true);
        txtState.setEnabled(true);
        txtZip.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPassword.setEnabled(true);
        txtTown.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Person person = userAccount.getPerson();
        
        person.setFirstName(txtFname.getText());
        person.setLastName(txtLname.getText());
        person.setCountry(txtCountry.getText());
        person.setState(txtState.getText());
        person.setAddress1(txtAddress.getText());
        person.setTown(txtTown.getText());
        person.setZipCode(txtZip.getText());
        person.setPhoneNumber(txtPhoneNo.getText());
        person.setEmailId(txtEmail.getText());
        
        userAccount.setUserName(txtUsername.getText());
        userAccount.setPassword(txtPassword.getText());
        JOptionPane.showMessageDialog(null, "Profile Updated Successfully");
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel address1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel emailID;
    private javax.swing.JLabel emailID1;
    private javax.swing.JLabel emailID2;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel town;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTown;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtZip;
    private javax.swing.JLabel zipCode;
    // End of variables declaration//GEN-END:variables

    private void display() {
        Person person = userAccount.getPerson();

        txtFname.setText(person.getFirstName());
        txtLname.setText(person.getLastName());
        txtCountry.setText(person.getCountry());
        txtState.setText(person.getState());
        txtAddress.setText(person.getAddress1());
        txtTown.setText(person.getTown());
        txtZip.setText(person.getZipCode());
        txtPhoneNo.setText(person.getPhoneNumber());
        txtEmail.setText(person.getEmailId());
        txtUsername.setText(userAccount.getUserName());
        txtPassword.setText(userAccount.getPassword());
    }
}
