/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.helpSeeker;

import business.EcoSystem;
import business.enterprisepkg.Enterprise;
import business.personpkg.Insurance;
import business.userAccountpkg.UserAccount;
import business.workQueuepkg.SendDataToInsurance;
import business.workQueuepkg.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.Insurance.InsuranceClaimsJPanel;

/**
 *
 * @author shrivatsanaragund
 */
public class PatientBuyInsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientBuyInsuranceJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;

    public PatientBuyInsuranceJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        basic = new javax.swing.JButton();
        standard = new javax.swing.JButton();
        premium = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIns = new javax.swing.JTable();
        btnBuy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBoughtInsurance = new javax.swing.JTable();
        btnClaim = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("MAX Life Insurance");

        basic.setText("Basic");
        basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicActionPerformed(evt);
            }
        });

        standard.setText("Standard");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        premium.setText("Premium");
        premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumActionPerformed(evt);
            }
        });

        tblIns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Plan", "Coverage", "Premium", "Benefits", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblIns);

        btnBuy.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        tblBoughtInsurance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Plan", "Coverage", "Premium", "Benefits", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblBoughtInsurance);

        btnClaim.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClaim.setText("Claim Insurance");
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(basic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(standard)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(premium))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 675, Short.MAX_VALUE)
                        .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClaim)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basic)
                    .addComponent(standard)
                    .addComponent(premium))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicActionPerformed

        DefaultTableModel model = (DefaultTableModel) tblIns.getModel();
        model.setRowCount(0);
        ArrayList<Insurance> insurance = ecoSystem.getPersonDirectory().getBasicInsuranceList();
        for (Insurance i : insurance) {
            Object row[] = new Object[10];
            row[0] = i.getPlan();
            row[1] = i.getCoverage();
            row[2] = i.getPremium();
            row[3] = i.getBenefits();
            model.addRow(row);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_basicActionPerformed

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblIns.getModel();
        model.setRowCount(0);
        ArrayList<Insurance> insurance = ecoSystem.getPersonDirectory().getStandardInsuranceList();
        for (Insurance i : insurance) {
            Object row[] = new Object[10];
            row[0] = i.getPlan();
            row[1] = i.getCoverage();
            row[2] = i.getPremium();
            row[3] = i.getBenefits();
            model.addRow(row);
        }
    }//GEN-LAST:event_standardActionPerformed

    private void premiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblIns.getModel();
        model.setRowCount(0);
        ArrayList<Insurance> insurance = ecoSystem.getPersonDirectory().getPremiumInsuranceList();
        for (Insurance i : insurance) {
            Object row[] = new Object[10];
            row[0] = i.getPlan();
            row[1] = i.getCoverage();
            row[2] = i.getPremium();
            row[3] = i.getBenefits();
            model.addRow(row);
        }
    }//GEN-LAST:event_premiumActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:

        // Get the selected row from the table
        int selectedRow = tblIns.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the selected insurance details
            String plan = tblIns.getValueAt(selectedRow, 0).toString();
            String coverage = tblIns.getValueAt(selectedRow, 1).toString();
            String premium = tblIns.getValueAt(selectedRow, 2).toString();
            String benefits = tblIns.getValueAt(selectedRow, 3).toString();

            Insurance selectedInsurance = new Insurance(plan, coverage, premium, benefits);

            userAccount.getPerson().getInsuranceList().add(selectedInsurance);

            DefaultTableModel boughtInsuranceModel = (DefaultTableModel) tblBoughtInsurance.getModel();
            Object row[] = new Object[]{plan, coverage, premium, benefits};
            boughtInsuranceModel.addRow(row);

            InsuranceClaimsJPanel insuranceClaimsPanel = new InsuranceClaimsJPanel(userProcessContainer, userAccount, enterprise, ecoSystem, selectedInsurance);
            userProcessContainer.add("InsuranceClaimsJPanel", insuranceClaimsPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

            JOptionPane.showMessageDialog(this, "Insurance bought successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Please select an insurance to buy.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        // TODO add your handling code here:
        //Date currentDate = new Date();
        int selectedRow = tblBoughtInsurance.getSelectedRow();

        if (selectedRow >= 0) {
            // Get the selected insurance details
            String plan = tblBoughtInsurance.getValueAt(selectedRow, 0).toString();
            String coverage = tblBoughtInsurance.getValueAt(selectedRow, 1).toString();
            String premium = tblBoughtInsurance.getValueAt(selectedRow, 2).toString();
            String benefits = tblBoughtInsurance.getValueAt(selectedRow, 3).toString();

            for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList()) {
                if (workRequest instanceof SendDataToInsurance) {
                    SendDataToInsurance sendDataRequest = (SendDataToInsurance) workRequest;
                    //String msg = txtComments.getText();
                    //sendDataRequest.setResolveDate(currentDate);
                    sendDataRequest.setPlan(plan);
                    sendDataRequest.setCoverage(coverage);
                    sendDataRequest.setPremium(premium);
                    sendDataRequest.setBenefit(benefits);
                }
            }
            JOptionPane.showMessageDialog(null, "Data Sent", "success", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Select a row");
        }
    }//GEN-LAST:event_btnClaimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basic;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnClaim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton premium;
    private javax.swing.JButton standard;
    private javax.swing.JTable tblBoughtInsurance;
    private javax.swing.JTable tblIns;
    // End of variables declaration//GEN-END:variables
}
