/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.government;

import business.EcoSystem;
import business.common.Validation;
import business.enterprisepkg.Enterprise;
import business.organizationpkg.DoctorOrganization;
import business.organizationpkg.Organization;
import business.organizationpkg.PatientOrganization;
import business.organizationpkg.PharmacyOrganization;
import business.personpkg.Patient;
import business.personpkg.Person;
import business.userAccountpkg.UserAccount;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author sameersdeshpande
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private PatientOrganization porg;

    public ReportJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        this.enterprise = enterprise;
              int patientsAbove60Count =3;
        populateText(patientsAbove60Count);
        populatePieChartData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageEnt1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        seniorsWithHeartPrbField = new javax.swing.JTextField();
        totTransReq1 = new javax.swing.JLabel();
        totalSeniorPpl = new javax.swing.JLabel();
        senShareInfoField = new javax.swing.JTextField();
        hasHeartPblm = new javax.swing.JLabel();
        senWithNoHeartProbField = new javax.swing.JTextField();
        txtTotalPatients = new javax.swing.JTextField();
        senWithSensorField = new javax.swing.JTextField();
        totalSeniorPpl1 = new javax.swing.JLabel();
        totalSeniorPpl2 = new javax.swing.JLabel();
        totalSeniorPpl3 = new javax.swing.JLabel();
        totalSeniorPpl4 = new javax.swing.JLabel();
        pieChartDetailedReportPanel = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        barchartBtn = new javax.swing.JButton();
        pieChartPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEnt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageEnt1.setText("Analytics");
        jPanel1.add(manageEnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 278, -1));

        jLayeredPane1.setBackground(new java.awt.Color(255, 51, 51));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        seniorsWithHeartPrbField.setEditable(false);
        seniorsWithHeartPrbField.setBackground(new java.awt.Color(255, 255, 255));

        totTransReq1.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N

        totalSeniorPpl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeniorPpl.setText("Total No of Senior Patients with aged above 60");

        senShareInfoField.setEditable(false);
        senShareInfoField.setBackground(new java.awt.Color(255, 255, 255));

        hasHeartPblm.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N

        senWithNoHeartProbField.setEditable(false);
        senWithNoHeartProbField.setBackground(new java.awt.Color(255, 255, 255));

        txtTotalPatients.setEditable(false);
        txtTotalPatients.setBackground(new java.awt.Color(255, 255, 255));

        senWithSensorField.setEditable(false);
        senWithSensorField.setBackground(new java.awt.Color(255, 255, 255));

        totalSeniorPpl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeniorPpl1.setText("Total No of Senior Patients with heart issues");

        totalSeniorPpl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeniorPpl2.setText("Total No of Child Patients with aged  less than 5");

        totalSeniorPpl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeniorPpl3.setText("Total No of Doctors");

        totalSeniorPpl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeniorPpl4.setText("Doctors to Patient ratio");

        jLayeredPane1.setLayer(seniorsWithHeartPrbField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totTransReq1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalSeniorPpl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(senShareInfoField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(hasHeartPblm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(senWithNoHeartProbField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtTotalPatients, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(senWithSensorField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalSeniorPpl1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalSeniorPpl2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalSeniorPpl3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(totalSeniorPpl4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasHeartPblm, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalSeniorPpl2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSeniorPpl3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSeniorPpl4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSeniorPpl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSeniorPpl1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(senShareInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totTransReq1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(senWithSensorField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senWithNoHeartProbField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seniorsWithHeartPrbField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSeniorPpl)
                    .addComponent(txtTotalPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasHeartPblm)
                    .addComponent(seniorsWithHeartPrbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSeniorPpl1))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senWithNoHeartProbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSeniorPpl2))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senWithSensorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSeniorPpl3))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totTransReq1)
                    .addComponent(senShareInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalSeniorPpl4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 445, -1));

        javax.swing.GroupLayout pieChartDetailedReportPanelLayout = new javax.swing.GroupLayout(pieChartDetailedReportPanel);
        pieChartDetailedReportPanel.setLayout(pieChartDetailedReportPanelLayout);
        pieChartDetailedReportPanelLayout.setHorizontalGroup(
            pieChartDetailedReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        pieChartDetailedReportPanelLayout.setVerticalGroup(
            pieChartDetailedReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(pieChartDetailedReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1147, 65, -1, -1));

        backJButton.setBackground(new java.awt.Color(102, 102, 255));
        backJButton.setText("<< Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 559, 93, -1));

        barchartBtn.setText("View Bar Chart");
        barchartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(barchartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 526, -1, -1));

        javax.swing.GroupLayout pieChartPanelLayout = new javax.swing.GroupLayout(pieChartPanel);
        pieChartPanel.setLayout(pieChartPanelLayout);
        pieChartPanelLayout.setHorizontalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pieChartPanelLayout.setVerticalGroup(
            pieChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(pieChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 65, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void barchartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchartBtnActionPerformed
    }//GEN-LAST:event_barchartBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton barchartBtn;
    private javax.swing.JLabel hasHeartPblm;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JPanel pieChartDetailedReportPanel;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JTextField senShareInfoField;
    private javax.swing.JTextField senWithNoHeartProbField;
    private javax.swing.JTextField senWithSensorField;
    private javax.swing.JTextField seniorsWithHeartPrbField;
    private javax.swing.JLabel totTransReq1;
    private javax.swing.JLabel totalSeniorPpl;
    private javax.swing.JLabel totalSeniorPpl1;
    private javax.swing.JLabel totalSeniorPpl2;
    private javax.swing.JLabel totalSeniorPpl3;
    private javax.swing.JLabel totalSeniorPpl4;
    private javax.swing.JTextField txtTotalPatients;
    // End of variables declaration//GEN-END:variables
public void populatePieChartData() {
        DefaultPieDataset dataSet = new DefaultPieDataset();
        int totalPatients = 0;
   
        int totalVolunteers = 0;
        int totalDonors = 0;
        int totalDrivers = 0;
        try {
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof PatientOrganization) {
                    this.porg = (PatientOrganization) organization;
                    totalPatients = organization.getPersonDirectory().getPersonList().size();
                }
            }
            try {
                //  this.vo = Validation.getVolunteerOrganization(ecoSystem, userAccount);
            } catch (NullPointerException npe) {
                JOptionPane.showMessageDialog(null, " Voluteer Organination does not exist!", "warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
      

            //dataSet.setValue("Total No of Doctors",35);
            dataSet.setValue("Total No of Patients", 15);
            System.out.println(totalPatients);
            dataSet.setValue("Total No of Doctors", 6);
            dataSet.setValue("Total patients above 60", 8);
            dataSet.setValue("Total patients belove 5", 3);
            //dataSet.setValue("Category D", 10);
//         dataSet.setValue("Total No of Volunteers", totalVolunteers );
//         dataSet.setValue("Total No of Donors",totalDonors);
//         dataSet.setValue("Total No of Drivers",totalDrivers);

            JFreeChart chart = ChartFactory.createPieChart3D("Pie Chart for " + userAccount.getNetwork().getCity(), dataSet, true, true, Locale.ENGLISH);
            chart.setBackgroundPaint(Color.WHITE);
            chart.getTitle().setPaint(Color.BLUE);
            ChartPanel chartpanel = new ChartPanel(chart);
            chartpanel.setDomainZoomable(true);

            pieChartPanel.setLayout(new BorderLayout());
            pieChartPanel.add(chartpanel, BorderLayout.EAST);
            pieChartPanel.setVisible(true);
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(null, " No Data to display as of now!", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }

    private void populateText(int patientsAbove60Count) {
patientsAbove60Count++;
  for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//                if (organization instanceof PatientOrganization) {
//                    this.porg = (PatientOrganization) organization;

                       ArrayList<UserAccount> patients = organization.getUserAccountDirectory().getUserAccountList();
                       System.out.println(patients);
                        for (UserAccount patient : patients) {
            // Check if the patient is above 60
            if (patient.getPerson().getAge() > 60) {
                patientsAbove60Count++;
                System.out.println(patientsAbove60Count);
                // Add more fields as needed
            }
        }
                        txtTotalPatients.setText(String.valueOf(patientsAbove60Count));
                }
            }
//    }
}
